Repository FuelLabs/fuel.nix, pull requests merged in 2023-08, with the labels that each got.

#94 Update README.md
  README.md
Labels: documentation

#96 Upload mac ARM build artifacts to cachix
  .github/workflows/ci.yml
  .github/workflows/refresh-manifests.yml
  script/cachix-push-paths.sh
  script/list-nix-store.sh
Labels: ci

#98 Add beta-4-rc-2 toolchain
  .github/workflows/ci.yml
  .github/workflows/refresh-manifests.yml
  milestones.nix
Labels: enhancement, fuel.nix
